export { default as RegisterPage } from "./registerPage/registerPage"
export { default as DashboardPage } from "./dashboardPage/dashboardPage"
export { default as EditPage } from "../pages/editPage/editPage"
export { default as FinalPage } from "./finalPage/finalPage"
export { default as SearPage } from "./searchPage/searchPage"